
import React, { useState, useMemo, useEffect } from 'react';
import { useNavigate, useParams, useLocation } from 'react-router-dom';
import { useData } from '../../context/DataContext';
import type { Customer, MaterialVariant, ProcessConfiguration, QuoteItem, ProductType, PrintPriceConfiguration, Quote, ProcessCalculationMethod } from '../../types';
import { CustomerModal } from '../../components/customers/CustomerModal';
import FormattedNumberInput from '../../components/FormattedNumberInput';
import { QuoteStatus } from '../../types';
import { CostingToolModal, AnalysisResults } from '../../components/accounting/CostingToolModal';
import { AccountingIcon, TrashIcon, ChevronDownIcon, ChevronRightIcon } from '../../components/icons/Icons';

type QuoteItemErrors = {
    productType?: string;
    productName?: string;
    quantity?: string;
    material?: string;
    printPriceConfigurationId?: string;
    details?: {
        size?: string;
        pages?: string;
    };
};

type FormErrors = {
    customerId?: string;
    items?: (QuoteItemErrors | null)[];
};

const QuoteItemForm: React.FC<{ 
    item: Partial<QuoteItem>; 
    onUpdate: (item: Partial<QuoteItem>) => void; 
    onRemove: () => void;
    onOpenCosting: () => void; 
    index: number;
    errors?: QuoteItemErrors | null;
    isDuplicate?: boolean;
}> = ({ item, onUpdate, onRemove, onOpenCosting, index, errors, isDuplicate = false }) => {
  const { materialGroups, materialVariants, processGroups, processConfigurations, printMethodGroups, printPriceConfigurations } = useData();
  const [isExpanded, setIsExpanded] = useState(true);

  const inputClass = (hasError: boolean) => 
    `w-full p-2 border rounded-lg bg-white dark:bg-gray-700 text-sm transition-colors focus:ring-2 focus:ring-blue-100 focus:border-blue-500 outline-none ${
      hasError ? 'border-red-500' : 'border-gray-300 dark:border-gray-600'
    }`;

  const labelClass = "block text-xs font-medium text-gray-500 dark:text-gray-400 mb-1 uppercase tracking-wider";

  useEffect(() => {
    let productName = item.productName || '';
    let isAutoGenerated = false;

    if (!productName && item.productType && item.productType !== 'Khác') {
        if (item.productType === 'Tờ rơi' && item.details?.size) {
            productName = `Tờ rơi ${item.details.size}`;
            isAutoGenerated = true;
        } else if (item.productType === 'Danh thiếp') {
            productName = `Danh thiếp`;
            isAutoGenerated = true;
        } else if (item.productType === 'Brochure' && item.details?.pages) {
            productName = `Brochure ${item.details.pages} trang`;
            isAutoGenerated = true;
        } else if (item.productType === 'Túi giấy' && item.details?.size) {
            productName = `Túi giấy ${item.details.size}`;
            isAutoGenerated = true;
        }
    }
    
    if (isAutoGenerated && productName !== item.productName) {
        onUpdate({ ...item, productName });
    }
  }, [item.productType, item.details, item.productName, onUpdate]);

  const handleMaterialChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedValue = e.target.value;
    const material = materialVariants.find(m => m.id === selectedValue);
    if (material) onUpdate({ ...item, material });
  };

  const handleProcessChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedIds = Array.from(e.target.selectedOptions, (option: HTMLOptionElement) => option.value);
    const selectedProcesses = processConfigurations.filter(p => selectedIds.includes(p.id));
    onUpdate({ ...item, processes: selectedProcesses });
  };
  
  const handleDetailsChange = (key: keyof QuoteItem['details'], value: any) => {
    onUpdate({ ...item, details: { ...item.details, [key]: value } });
  };
  
  const getPrintConfigLabel = (config: PrintPriceConfiguration) => {
    return config.name;
  };
  
  const getProcessConfigLabel = (config: ProcessConfiguration) => {
    let priceStr = '';
    switch(config.calculationMethod) {
        case 'theo_lo':
            priceStr = `${config.unitPrice.toLocaleString('vi-VN')}đ/lô`;
            break;
        case 'theo_thanh_pham':
        case 'theo_to_in':
            priceStr = `${config.unitPrice.toLocaleString('vi-VN')}đ/${config.pricingUnit}`;
            if (config.setupFee > 0) {
                priceStr = `${config.setupFee.toLocaleString('vi-VN')}đ + ${priceStr}`;
            }
            break;
    }
    return `${config.name} (+${priceStr})`;
  };

  return (
    <div className={`bg-white dark:bg-gray-800 rounded-xl border shadow-sm transition-all duration-200 ${isDuplicate ? 'border-red-500 ring-1 ring-red-500' : 'border-gray-200 dark:border-gray-700 hover:border-blue-300'}`}>
        
        {/* Header Bar */}
        <div 
            className="flex justify-between items-center px-4 py-3 bg-gray-50 dark:bg-gray-900/50 cursor-pointer rounded-t-xl"
            onClick={() => setIsExpanded(!isExpanded)}
        >
            <div className="flex items-center gap-3">
                <button type="button" className="text-gray-400 hover:text-gray-600">
                    {isExpanded ? <ChevronDownIcon className="w-4 h-4" /> : <ChevronRightIcon className="w-4 h-4" />}
                </button>
                <span className="font-bold text-gray-700 dark:text-gray-200">#{index + 1}</span>
                <h3 className="font-semibold text-gray-900 dark:text-white text-base">
                    {item.productName || 'Sản phẩm mới'}
                </h3>
                {item.totalPrice ? <span className="text-sm font-medium text-green-600 bg-green-50 px-2 py-0.5 rounded-md border border-green-100">{item.totalPrice.toLocaleString('vi-VN')} đ</span> : null}
                {isDuplicate && <span className="text-xs font-bold text-red-600 bg-red-100 px-2 py-0.5 rounded-full">TRÙNG LẶP</span>}
            </div>
            <div className="flex items-center gap-2" onClick={e => e.stopPropagation()}>
                <button 
                    type="button" 
                    onClick={onOpenCosting}
                    className="flex items-center gap-1.5 text-xs font-semibold text-blue-700 bg-blue-100 hover:bg-blue-200 px-3 py-1.5 rounded-md transition-colors"
                >
                    <AccountingIcon className="w-4 h-4"/> Tính giá
                </button>
                <button type="button" onClick={onRemove} className="text-gray-400 hover:text-red-500 p-1.5 rounded-md hover:bg-gray-200 transition-colors"><TrashIcon className="w-4 h-4" /></button>
            </div>
        </div>

        {isExpanded && (
        <div className="p-5 space-y-6">
            {/* Product Basic Info */}
            <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
                <div className="md:col-span-3">
                    <label className={labelClass}>Loại sản phẩm</label>
                    <select
                        value={item.productType || ''}
                        onChange={e => onUpdate({ ...item, productType: e.target.value as ProductType, details: {} })}
                        className={inputClass(!!errors?.productType)}
                    >
                        <option value="" disabled>Chọn loại</option>
                        <option value="Tờ rơi">Tờ rơi</option>
                        <option value="Brochure">Brochure</option>
                        <option value="Danh thiếp">Danh thiếp</option>
                        <option value="Túi giấy">Túi giấy</option>
                        <option value="Khác">Khác</option>
                    </select>
                </div>
                <div className="md:col-span-5">
                    <label className={labelClass}>Tên sản phẩm</label>
                    <input 
                        type="text" 
                        value={item.productName || ''} 
                        onChange={e => onUpdate({ ...item, productName: e.target.value })} 
                        className={inputClass(!!errors?.productName)}
                        placeholder="VD: Tờ rơi khai trương..."
                    />
                </div>
                 <div className="md:col-span-2">
                    <label className={labelClass}>Số lượng</label>
                    <FormattedNumberInput 
                        value={item.quantity || ''} 
                        onChange={val => onUpdate({ ...item, quantity: val })} 
                        className={inputClass(!!errors?.quantity)}
                    />
                 </div>
                 <div className="md:col-span-2">
                    <label className={labelClass}>Thành tiền (VND)</label>
                    <FormattedNumberInput 
                        value={item.totalPrice || ''} 
                        onChange={val => onUpdate({ ...item, totalPrice: val })} 
                        className="w-full p-2 border rounded-lg bg-gray-50 text-right font-bold text-gray-800 border-gray-300 focus:ring-2 focus:ring-green-500 focus:border-green-500" 
                    />
                 </div>
            </div>
            
            {/* Specifications Section */}
            <div className="bg-gray-50 dark:bg-gray-800/50 rounded-lg p-4 border border-gray-100 dark:border-gray-700">
                <h4 className="text-sm font-bold text-gray-700 dark:text-gray-300 mb-3 uppercase border-b pb-2 border-gray-200 dark:border-gray-600">Quy cách kỹ thuật</h4>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                    {/* Size/Dimensions */}
                    <div>
                        <label className={labelClass}>Kích thước (TP)</label>
                        <input 
                            type="text" 
                            value={item.details?.size || ''} 
                            onChange={(e) => handleDetailsChange('size', e.target.value)}
                            className={inputClass(!!errors?.details?.size)}
                            placeholder="VD: A5 hoặc 14.8x21cm"
                        />
                    </div>
                     {/* Pages (if Brochure/Book) */}
                    {item.productType === 'Brochure' || item.productType === 'Khác' ? (
                        <div>
                            <label className={labelClass}>Số trang</label>
                            <FormattedNumberInput 
                                value={item.details?.pages || ''} 
                                onChange={(val) => handleDetailsChange('pages', val)} 
                                className={inputClass(false)} 
                                placeholder="VD: 12"
                            />
                        </div>
                    ) : null}
                     {/* Paper GSM */}
                    <div>
                        <label className={labelClass}>Định lượng (GSM)</label>
                        <FormattedNumberInput 
                            value={item.details?.gsm || ''} 
                            onChange={(val) => handleDetailsChange('gsm', val)} 
                            className={inputClass(false)} 
                            placeholder="VD: 150"
                        />
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Material Selection */}
                    <div>
                        <label className={labelClass}>Chất liệu</label>
                        <select 
                            value={item.material?.id || ''} 
                            onChange={handleMaterialChange} 
                            className={inputClass(!!errors?.material)}
                        >
                            <option value="">Chọn chất liệu</option>
                            {materialGroups.map(group => (
                                <optgroup key={group.id} label={group.name}>
                                    {materialVariants
                                        .filter(variant => variant.groupId === group.id)
                                        .map(variant => (
                                            <option key={variant.id} value={variant.id}>
                                                {variant.name} ({variant.purchaseUnit})
                                            </option>
                                        ))
                                    }
                                </optgroup>
                            ))}
                        </select>
                    </div>
                    
                    {/* Print Config */}
                    <div>
                         <label className={labelClass}>Quy cách in</label>
                        <select 
                            value={item.printPriceConfigurationId || ''} 
                            onChange={e => onUpdate({ ...item, printPriceConfigurationId: e.target.value })} 
                            className={inputClass(!!errors?.printPriceConfigurationId)}
                        >
                            <option value="">Chọn quy cách in</option>
                            {printMethodGroups.map(group => (
                                <optgroup key={group.id} label={group.name}>
                                    {printPriceConfigurations
                                        .filter(config => config.groupId === group.id)
                                        .map(config => (
                                            <option key={config.id} value={config.id}>
                                                {getPrintConfigLabel(config)}
                                            </option>
                                        ))
                                    }
                                </optgroup>
                            ))}
                        </select>
                    </div>
                </div>

                {/* Finishing Processes */}
                <div className="mt-4">
                     <label className={labelClass}>Gia công sau in</label>
                     <div className="relative">
                        <select 
                            multiple 
                            value={(item.processes || []).map(p => p.id)} 
                            onChange={handleProcessChange} 
                            className={`${inputClass(false)} h-24`}
                        >
                        {processGroups.map(group => (
                            <optgroup key={group.id} label={group.name}>
                                {processConfigurations
                                    .filter(config => config.groupId === group.id)
                                    .map(config => (
                                        <option key={config.id} value={config.id}>
                                            {getProcessConfigLabel(config)}
                                        </option>
                                    ))
                                }
                            </optgroup>
                        ))}
                        </select>
                        <p className="text-xs text-gray-400 mt-1 italic">* Giữ Ctrl (Window) hoặc Command (Mac) để chọn nhiều mục.</p>
                    </div>
                </div>
            </div>
        </div>
        )}
    </div>
  );
};


const QuoteCreatePage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const isEditMode = !!id;
  const location = useLocation();

  const { customers, addQuote, updateQuote, getQuoteById, addCustomer, companyInfo, materialVariants, processConfigurations } = useData();
  const navigate = useNavigate();
  const [customerId, setCustomerId] = useState<string>('');
  const [items, setItems] = useState<Partial<QuoteItem>[]>([
    { id: crypto.randomUUID(), productType: 'Tờ rơi', details: { resolution: 'Tiêu chuẩn' }, processes: [] }
  ]);
  const [isCustomerModalOpen, setIsCustomerModalOpen] = useState(false);
  const [costingModalOpen, setCostingModalOpen] = useState(false);
  const [activeCostingItemIndex, setActiveCostingItemIndex] = useState<number | null>(null);
  const [errors, setErrors] = useState<FormErrors>({});
  const [generalErrors, setGeneralErrors] = useState<string[]>([]);
  const [duplicateItemIds, setDuplicateItemIds] = useState<Set<string>>(new Set());
  
  useEffect(() => {
    const state = location.state as { prefillItems?: Partial<QuoteItem>[] } | null;

    if (isEditMode && id) {
        const quoteToEdit = getQuoteById(id);
        if (quoteToEdit) {
            if (quoteToEdit.status !== QuoteStatus.Draft) {
                setGeneralErrors(['Chỉ có thể sửa báo giá ở trạng thái "Mới".']);
                setTimeout(() => navigate(`/quotes`), 3000);
                return;
            }
            setCustomerId(quoteToEdit.customer.id);
            setItems(JSON.parse(JSON.stringify(quoteToEdit.items)));
        } else {
            setGeneralErrors(['Không tìm thấy báo giá.']);
            setTimeout(() => navigate('/quotes'), 3000);
        }
    } else if (state?.prefillItems && Array.isArray(state.prefillItems)) {
        const prefilledItemsWithIds = (state.prefillItems as Partial<QuoteItem>[]).map(item => ({
            ...item,
            id: item.id || crypto.randomUUID(),
        }));
        setItems(prefilledItemsWithIds);
        navigate(location.pathname, { replace: true, state: {} });
    } else if (!isEditMode && state === null) {
        setCustomerId('');
        setItems([{ id: crypto.randomUUID(), productType: 'Tờ rơi', details: { resolution: 'Tiêu chuẩn' }, processes: [] }]);
    }
  }, [id, isEditMode, getQuoteById, navigate, location.state]);
  
  const handleAddItem = () => setItems([...items, { id: crypto.randomUUID(), productType: 'Tờ rơi', details: { resolution: 'Tiêu chuẩn' }, processes: [] }]);
  const handleRemoveItem = (index: number) => setItems(items.filter((_, i) => i !== index));
  const handleUpdateItem = (index: number, updatedItem: Partial<QuoteItem>) => {
    const newItems = [...items];
    newItems[index] = updatedItem;
    setItems(newItems);
  };

  const handleOpenCostingTool = (index: number) => {
      setActiveCostingItemIndex(index);
      setCostingModalOpen(true);
  };

  const handleApplyCosting = (result: AnalysisResults) => {
      if (activeCostingItemIndex === null) return;
      
      const { inputs, costs, generalInfo } = result;
      const currentItem = items[activeCostingItemIndex];
      
      const selectedProcesses = processConfigurations.filter(p => inputs.selectedProcessIds.includes(p.id));

      const updatedItem: Partial<QuoteItem> = {
          ...currentItem,
          productName: generalInfo.productName,
          quantity: Number(generalInfo.quantity),
          totalPrice: costs.totalPrice,
          productType: inputs.productType === 'bag' ? 'Túi giấy' : inputs.productType === 'catalogue' ? 'Brochure' : 'Tờ rơi',
          material: materialVariants.find(m => m.id === result.analysis.bestLayout.paperId),
          processes: selectedProcesses,
          details: {
              ...currentItem.details,
              size: generalInfo.dimensions,
              gsm: undefined, 
              pages: inputs.pages ? Number(inputs.pages) : undefined,
          },
          printPriceConfigurationId: inputs.selectedPrintPriceConfigId,
      };
      
      handleUpdateItem(activeCostingItemIndex, updatedItem);
  };

  const totalAmount = useMemo(() => items.reduce((sum, item) => sum + (item.totalPrice || 0), 0), [items]);

  const handleSaveCustomer = (customerData: Omit<Customer, 'id'> | Customer, saveAndNew: boolean) => {
    const { id, ...newCustomerData } = customerData as Customer;
    const createdCustomer = addCustomer(newCustomerData);
    setCustomerId(createdCustomer.id);
    setIsCustomerModalOpen(false);
  };

  const validateForm = (): boolean => {
    setErrors({});
    setGeneralErrors([]);
    setDuplicateItemIds(new Set());

    const newErrors: FormErrors = {};
    const highLevelErrors: string[] = [];
    let isValid = true;

    if (!customerId) {
        newErrors.customerId = "Vui lòng chọn khách hàng.";
        isValid = false;
    }

    if (items.length === 0) {
       highLevelErrors.push('Vui lòng thêm ít nhất một sản phẩm vào báo giá.');
       isValid = false;
    }
    
    const itemErrors: (QuoteItemErrors | null)[] = items.map(item => {
        const errors: QuoteItemErrors = {};
        if (!item.productType) errors.productType = "Vui lòng chọn loại sản phẩm.";
        if (item.productType === 'Khác' && !item.productName?.trim()) errors.productName = "Vui lòng nhập tên sản phẩm.";
        if (!item.quantity || item.quantity <= 0) errors.quantity = "Số lượng phải lớn hơn 0.";
        if (!item.material) errors.material = "Vui lòng chọn chất liệu.";
        return Object.keys(errors).length > 0 ? errors : null;
    });

    if (itemErrors.some(e => e !== null)) {
        newErrors.items = itemErrors;
        isValid = false;
    }
    
    setErrors(newErrors);
    setGeneralErrors(highLevelErrors);
    return isValid;
  };


  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) {
        return;
    }

    const customer = customers.find(c => c.id === customerId);
    if (!customer) {
        setGeneralErrors(['Khách hàng đã chọn không hợp lệ.']);
        return;
    }

    const finalItems = items.map((item) => ({
      ...item,
      id: item.id!, 
      details: item.details || {},
      printPriceConfigurationId: item.printPriceConfigurationId || '',
      processes: item.processes || [],
    })) as QuoteItem[];

    const vatRate = companyInfo.vatRate || 0;
    const vatAmount = totalAmount - (totalAmount / (1 + vatRate / 100));

    if (isEditMode && id) {
        const originalQuote = getQuoteById(id);
        if (!originalQuote) {
            setGeneralErrors(["Lỗi: Không tìm thấy báo giá gốc để cập nhật."]);
            return;
        }
        const updatedQuote: Quote = {
            ...originalQuote,
            customer,
            items: finalItems,
            totalAmount,
            vatAmount,
        };
        updateQuote(updatedQuote);
        navigate('/quotes');
    } else {
        addQuote({ customer, items: finalItems, totalAmount, vatAmount });
        navigate('/quotes');
    }
  };

  return (
    <>
    <form onSubmit={handleSubmit} className="space-y-8 max-w-5xl mx-auto pb-10">
      <div className="flex justify-between items-center">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">{isEditMode ? `Chỉnh sửa Báo giá #${id}` : 'Tạo Báo giá mới'}</h1>
      </div>
      
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 space-y-4">
        <div className="flex items-center space-x-3 mb-2">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-600 text-white font-bold text-base flex-shrink-0">1</span>
            <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-100">Thông tin khách hàng</h2>
        </div>
        <div className="flex items-center space-x-2 pl-11">
            <div className="w-full">
                <select value={customerId} onChange={e => setCustomerId(e.target.value)} className={`w-full p-2 border rounded-lg bg-gray-50 dark:bg-gray-700 text-sm ${errors.customerId ? 'border-red-500' : 'border-gray-300 dark:border-gray-600'}`} required>
                    <option value="">-- Chọn khách hàng --</option>
                    {customers.map(c => <option key={c.id} value={c.id}>{c.name} - {c.phone}</option>)}
                </select>
                {errors.customerId && <p className="text-red-500 text-xs mt-1">{errors.customerId}</p>}
            </div>
            <button type="button" onClick={() => setIsCustomerModalOpen(true)} className="flex-shrink-0 bg-green-500 text-white px-4 py-2 rounded-lg font-semibold hover:bg-green-600 transition whitespace-nowrap text-sm">
                + Khách mới
            </button>
        </div>
      </div>

      <div className="space-y-6">
        <div className="flex items-center space-x-3 px-1">
            <span className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-600 text-white font-bold text-base flex-shrink-0">2</span>
            <h2 className="text-lg font-semibold text-gray-800 dark:text-gray-100">Chi tiết sản phẩm báo giá</h2>
        </div>
        
        <div className="space-y-4 pl-0 md:pl-0">
            {items.map((item, index) => (
                <QuoteItemForm 
                    key={item.id || index} 
                    index={index} 
                    item={item} 
                    onUpdate={(updated) => handleUpdateItem(index, updated)} 
                    onRemove={() => handleRemoveItem(index)} 
                    onOpenCosting={() => handleOpenCostingTool(index)}
                    errors={errors.items?.[index]} 
                    isDuplicate={duplicateItemIds.has(item.id!)} 
                />
            ))}
             <button type="button" onClick={handleAddItem} className="w-full py-3 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-xl text-gray-500 font-semibold hover:border-blue-500 hover:text-blue-600 transition flex items-center justify-center gap-2">
                + Thêm dòng sản phẩm
            </button>
        </div>
      </div>

      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 sticky bottom-0 z-10">
        <div className="flex justify-between items-center">
            <div>
                {generalErrors.map((err, i) => <p key={i} className="text-red-500 font-bold mb-2">{err}</p>)}
                <p className="text-lg font-bold text-gray-800 dark:text-white">Tổng cộng: {totalAmount.toLocaleString('vi-VN')} đ</p>
                <p className="text-sm text-gray-500">VAT ({companyInfo.vatRate}%): {(totalAmount * companyInfo.vatRate / 100).toLocaleString('vi-VN')} đ</p>
            </div>
            <div className="flex items-center space-x-3">
                <button type="button" onClick={() => navigate('/quotes')} className="px-6 py-3 rounded-lg font-semibold text-gray-700 bg-gray-200 hover:bg-gray-300 transition">
                    Hủy
                </button>
                <button type="submit" className="px-8 py-3 rounded-lg font-bold text-white bg-blue-600 hover:bg-blue-700 shadow-lg transition transform hover:-translate-y-0.5">
                    {isEditMode ? 'Lưu Báo giá' : 'Tạo Báo giá'}
                </button>
            </div>
        </div>
      </div>
    </form>
    {isCustomerModalOpen && <CustomerModal customer={null} onClose={() => setIsCustomerModalOpen(false)} onSave={handleSaveCustomer} showSaveAndNew={false} />}
    {costingModalOpen && (
        <CostingToolModal 
            onClose={() => setCostingModalOpen(false)} 
            onApply={handleApplyCosting}
        />
    )}
    </>
  );
};
export default QuoteCreatePage;
